export const keywords = [
  "Business Lecture",
  "Services Lecture",
  "IT Services Lecture",
  "Web Development Lecture",
  "SEO Lecture",
  "Data Analysis Lecture",
  "Marketing Lecture",
  "B2B Lecture",
  "SaaS Lecture",
  "Consulting Lecture",
  "Aelluminate Lecture",
  "Aelluminate Business Services Lecture",
  "Digital Transformation Lecture",
  "E-commerce Solutions Lecture",
  "Mobile App Development Lecture",
  "Project Management Lecture",
  "Business Intelligence Lecture",
  "Customer Relationship Management Lecture",
  "Enterprise Solutions Lecture",
  "Software Development Lecture",
  "Technology Consulting Lecture",
  "IT Support Lecture",
  "Data Management Lecture",
  "Business Strategy Lecture",
  "Innovation Lecture",
  "Tech Solutions Lecture",
  "Digital Marketing Lecture",
  "Content Marketing Lecture",
  "Social Media Marketing Lecture",
  "Email Marketing Lecture",
  "Lead Generation Lecture",
  "Market Research Lecture",
  "Brand Strategy Lecture",
  "User Experience Lecture",
  "Business Projects",
  "Services Projects",
  "IT Services Projects",
  "Web Development Projects",
  "SEO Projects",
  "Data Analysis Projects",
  "Marketing Projects",
  "B2B Projects",
  "SaaS Projects",
  "Consulting Projects",
  "Aelluminate Projects",
  "Aelluminate Business Services Projects",
  "Digital Transformation Projects",
  "E-commerce Solutions Projects",
  "Mobile App Development Projects",
  "Project Management Projects",
  "Business Intelligence Projects",
  "Customer Relationship Management Projects",
  "Enterprise Solutions Projects",
  "Software Development Projects",
  "Technology Consulting Projects",
  "IT Support Projects",
  "Data Management Projects",
  "Business Strategy Projects",
  "Innovation Projects",
  "Tech Solutions Projects",
  "Digital Marketing Projects",
  "Content Marketing Projects",
  "Social Media Marketing Projects",
  "Email Marketing Projects",
  "Lead Generation Projects",
  "Market Research Projects",
  "Brand Strategy Projects",
  "User Experience Projects",
  "Business Blog",
  "Services Blog",
  "IT Services Blog",
  "Web Development Blog",
  "SEO Blog",
  "Data Analysis Blog",
  "Marketing Blog",
  "B2B Blog",
  "SaaS Blog",
  "Consulting Blog",
  "Aelluminate Blog",
  "Aelluminate Business Services Blog",
  "Digital Transformation Blog",
  "E-commerce Solutions Blog",
  "Mobile App Development Blog",
  "Project Management Blog",
  "Business Intelligence Blog",
  "Customer Relationship Management Blog",
  "Enterprise Solutions Blog",
  "Software Development Blog",
  "Technology Consulting Blog",
  "IT Support Blog",
  "Data Management Blog",
  "Business Strategy Blog",
  "Innovation Blog",
  "Tech Solutions Blog",
  "Digital Marketing Blog",
  "Content Marketing Blog",
  "Social Media Marketing Blog",
  "Email Marketing Blog",
  "Lead Generation Blog",
  "Market Research Blog",
  "Brand Strategy Blog",
  "User Experience Blog",
]
